-- MySQL Script generated by MySQL Workbench
-- 11/24/18 23:50:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SGOM
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SGOM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SGOM` DEFAULT CHARACTER SET utf8 ;
USE `SGOM` ;

-- -----------------------------------------------------
-- Table `SGOM`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGOM`.`CLIENTE` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(18) NOT NULL,
  `NOME` VARCHAR(60) NOT NULL,
  `DATA_NASC` DATE NOT NULL,
  `TELEFONE` VARCHAR(11) NULL,
  `RG` VARCHAR(15) NOT NULL,
  `ENDERECO` VARCHAR(60) NULL,
  `SEXO` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGOM`.`FUNCIONARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGOM`.`FUNCIONARIO` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(18) NOT NULL,
  `NOME` VARCHAR(60) NOT NULL,
  `DATA_NASC` DATE NOT NULL,
  `TELEFONE` VARCHAR(11) NULL,
  `RG` VARCHAR(15) NOT NULL,
  `ENDERECO` VARCHAR(60) NULL,
  `PAPEL` SMALLINT NOT NULL,
  `LOGIN` VARCHAR(20) NOT NULL,
  `SENHA` VARCHAR(20) NOT NULL,
  `FOTO` VARCHAR(200) NULL,
  `SEXO` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `LOGIN_UNIQUE` (`LOGIN` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGOM`.`NOTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGOM`.`NOTA` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `DATA` DATE NOT NULL,
  `DESCRICAO` VARCHAR(250) NOT NULL,
  `PECAS` VARCHAR(45) NULL,
  `VALOR` DECIMAL(8,2) NOT NULL,
  `SITUACAO` VARCHAR(45) NULL,
  `CLIENTE_ID` INT UNSIGNED NOT NULL,
  `FUNCIONARIO_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_NOTA_CLIENTE_idx` (`CLIENTE_ID` ASC),
  INDEX `fk_NOTA_FUNCIONARIO1_idx` (`FUNCIONARIO_ID` ASC),
  CONSTRAINT `fk_NOTA_CLIENTE`
    FOREIGN KEY (`CLIENTE_ID`)
    REFERENCES `SGOM`.`CLIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NOTA_FUNCIONARIO1`
    FOREIGN KEY (`FUNCIONARIO_ID`)
    REFERENCES `SGOM`.`FUNCIONARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGOM`.`PECA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGOM`.`PECA` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `DESCRICAO` VARCHAR(45) NULL,
  `QTDE` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SGOM`.`DESPESAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SGOM`.`DESPESAS` (
  `ID` INT NULL AUTO_INCREMENT,
  `DESCRICAO` VARCHAR(100) NOT NULL,
  `VALOR` DECIMAL(8,2) UNSIGNED NOT NULL,
  `SITUACAO` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

show databases;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




INSERT INTO FUNCIONARIO VALUES(null,"055.563.265-98", "Fernando Furtado", "2005-04-15", "9 9999-9999", "568931", "Rua A", 2, "admin", "admin", null, "MASCULINO");

select * from peca;

